# ----------------------------------------------------------------------------
#
# Package             : zm-db-conf
# Source Repo         : https://github.com/Zimbra/zm-db-conf
# Travis Job Link     : https://travis-ci.com/github/asellappen/zm-db-conf/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: java

arch:
    - amd64
    - ppc64le

dist: bionic

before_script:
  - wget https://github.com/Zimbra/zm-zcs/archive/refs/heads/master.zip -O /tmp/zcs.gz
  - unzip /tmp/zcs.gz
  - cp -pr zm-zcs-master/ ../
  - sed 's/zm-zcs/zm-zcs-master/g' build.xml >tmp
  - mv tmp build.xml
  - pwd
  - ls -ltr
#  - export PATH=$PATH:$PWD/casperjs-1.0.2/bin/
    
install:
   - sudo apt update
   - sudo apt install ant

script:

   - ant
