# ----------------------------------------------------------------------------
#
# Package             : zm-db-conf
# Source Repo         : https://github.com/Zimbra/zm-db-conf
# Travis Job Link     : https://travis-ci.com/github/asellappen/zm-db-conf/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: java

arch:
    - amd64
    - ppc64le

dist: bionic

addons:
  apt:
    packages: https://github.com/Zimbra/zm-zcs  
    
install:

   - sudo apt update
   - sudo apt install ant

script:

   - ant
